platform :ios, '13.0'

inhibit_all_warnings!

target 'TestTask' do
  use_frameworks!

  pod 'NeedleFoundation', '~> 0.17'
  pod 'SnapKit', '~> 5.0'
  pod 'Kingfisher', '~> 7.0'

  target 'TestTaskTests' do
    inherit! :search_paths
  end

  target 'TestTaskUITests' do
  end

end
